import { ShortcutLibrary } from './types';

export const MASTER_DB: ShortcutLibrary = {
  "Productivity - Notion": [
    { id: "n1", label: "Highlight text", keys: "Cmd+Shift+H" },
    { id: "n2", label: "Dark/Light Mode", keys: "Cmd+Shift+L" },
    { id: "n3", label: "Open link new tab", keys: "Cmd+Click" },
    { id: "n4", label: "Export page", keys: "Cmd+Shift+E" },
    { id: "n5", label: "Create Ordered List", keys: "Cmd+Shift+7" },
    { id: "n6", label: "Create Bullet List", keys: "Cmd+Shift+8" },
    { id: "n7", label: "Turn into Page", keys: "Cmd+Opt+P" },
    { id: "n8", label: "Turn into To-Do", keys: "Cmd+Opt+4" },
    { id: "n9", label: "Zoom In", keys: "Cmd+Plus" },
    { id: "n10", label: "Zoom Out", keys: "Cmd+Minus" },
    { id: "n11", label: "Heading 1", keys: "Cmd+Opt+1" },
    { id: "n12", label: "Heading 2", keys: "Cmd+Opt+2" },
    { id: "n13", label: "Heading 3", keys: "Cmd+Opt+3" },
    { id: "n14", label: "Toggle List", keys: "Cmd+Opt+7" },
    { id: "n15", label: "Quote Block", keys: "Cmd+Opt+5" },
    { id: "n16", label: "Divider", keys: "---" },
    { id: "n17", label: "Duplicate Block", keys: "Cmd+D" },
    { id: "n18", label: "Move Block Up", keys: "Cmd+Shift+Up" },
    { id: "n19", label: "Move Block Down", keys: "Cmd+Shift+Down" },
    { id: "n20", label: "Open Search", keys: "Cmd+P" },
    { id: "n21", label: "Go Back", keys: "Cmd+[" },
    { id: "n22", label: "Go Forward", keys: "Cmd+]" },
  ],
  "Productivity - Notion Calendar": [
    { id: "nc1", label: "Go to Today", keys: "T" },
    { id: "nc2", label: "Add Focus Block", keys: "Cmd+Shift+F" },
    { id: "nc3", label: "Create Event", keys: "C" },
    { id: "nc4", label: "Switch Views", keys: "V" },
    { id: "nc5", label: "Show Invites", keys: "I" },
    { id: "nc6", label: "Next Range", keys: "N" },
    { id: "nc7", label: "Prev Range", keys: "P" },
    { id: "nc8", label: "Connect Cal", keys: "Cmd+K" },
    { id: "nc9", label: "Join Meeting", keys: "Cmd+J" },
    { id: "nc10", label: "Day View", keys: "D" },
    { id: "nc11", label: "Week View", keys: "W" },
    { id: "nc12", label: "Month View", keys: "M" },
  ],
  "AI - ChatGPT": [
    { id: "cg1", label: "Scroll to Bottom", keys: "Ctrl+Shift+S" },
    { id: "cg2", label: "Focus Input", keys: "Shift+Esc" },
    { id: "cg3", label: "Nav Messages", keys: "Ctrl+Up/Down" },
    { id: "cg4", label: "Regenerate", keys: "Ctrl+R" },
    { id: "cg5", label: "Search/History", keys: "Ctrl+K" },
    { id: "cg6", label: "Copy Last Code", keys: "Ctrl+Shift+C" },
    { id: "cg7", label: "New Chat", keys: "Ctrl+Shift+O" },
    { id: "cg8", label: "Delete Chat", keys: "Ctrl+Shift+Backspace" },
    { id: "cg9", label: "Show Shortcuts", keys: "Ctrl+/" },
  ],
  "AI - Gemini": [
    { id: "gm1", label: "New Chat", keys: "Ctrl+Shift+N" },
    { id: "gm2", label: "Toggle Sidebar", keys: "Ctrl+H" },
    { id: "gm3", label: "Switch History", keys: "Ctrl+1-9" },
    { id: "gm4", label: "Toggle Exts", keys: "Ctrl+E" },
    { id: "gm5", label: "Dark Mode", keys: "Ctrl+Shift+D" },
    { id: "gm6", label: "Focus Input", keys: "/" },
    { id: "gm7", label: "Stop Generating", keys: "Esc" },
  ],
  "AI - Claude": [
    { id: "cl1", label: "New Chat", keys: "Ctrl+Shift+N" },
    { id: "cl2", label: "Toggle History", keys: "Ctrl+Shift+H" },
    { id: "cl3", label: "Focus Prev/Next", keys: "Ctrl+Up/Down" },
    { id: "cl4", label: "Settings", keys: "Ctrl+P" },
    { id: "cl5", label: "Attach File", keys: "Ctrl+Shift+U" },
  ],
  "Dev - CLI / Terminal": [
    { id: "cli1", label: "Del Word Before", keys: "Ctrl+W" },
    { id: "cli2", label: "Del to End", keys: "Ctrl+K" },
    { id: "cli3", label: "Paste Killed", keys: "Ctrl+Y" },
    { id: "cli4", label: "Transpose Char", keys: "Ctrl+T" },
    { id: "cli5", label: "Fwd Word", keys: "Alt+F" },
    { id: "cli6", label: "Back Word", keys: "Alt+B" },
    { id: "cli7", label: "Exec/Fetch Next", keys: "Ctrl+O" },
    { id: "cli8", label: "Clear Screen", keys: "Ctrl+L" },
    { id: "cli9", label: "Search History", keys: "Ctrl+R" },
    { id: "cli10", label: "Go to Start", keys: "Ctrl+A" },
    { id: "cli11", label: "Go to End", keys: "Ctrl+E" },
  ],
  "Dev - VS Code": [
    { id: "v1", label: "Select All Occurrences", keys: "Ctrl+Shift+L" },
    { id: "v2", label: "Go to Symbol", keys: "Ctrl+Shift+O" },
    { id: "v3", label: "Add Line Comment", keys: "Ctrl+K, C" },
    { id: "v4", label: "Rem Line Comment", keys: "Ctrl+K, U" },
    { id: "v5", label: "Search All Files", keys: "Ctrl+Shift+F" },
    { id: "v6", label: "Source Control", keys: "Ctrl+Shift+G" },
    { id: "v7", label: "Close Tab", keys: "Ctrl+W" },
    { id: "v8", label: "Copy Line Up/Down", keys: "Alt+Shift+Up/Dn" },
    { id: "v9", label: "Toggle Panel", keys: "Ctrl+J" },
    { id: "v10", label: "Command Palette", keys: "Ctrl+Shift+P" },
    { id: "v11", label: "Go to File", keys: "Ctrl+P" },
    { id: "v12", label: "Split Editor", keys: "Ctrl+\\" },
    { id: "v13", label: "Toggle Terminal", keys: "Ctrl+`" },
    { id: "v14", label: "Move Line Up", keys: "Alt+Up" },
    { id: "v15", label: "Move Line Down", keys: "Alt+Down" },
    { id: "v16", label: "Fold Code", keys: "Ctrl+Shift+[" },
    { id: "v17", label: "Unfold Code", keys: "Ctrl+Shift+]" },
    { id: "v18", label: "Format Document", keys: "Shift+Alt+F" },
    { id: "v19", label: "Go to Definition", keys: "F12" },
    { id: "v20", label: "Peek Definition", keys: "Alt+F12" },
  ],
  "Dev - GitHub": [
    { id: "gh1", label: "Shortcuts Help", keys: "Shift+?" },
    { id: "gh2", label: "New Discussion", keys: "G, D" },
    { id: "gh3", label: "Mark Read", keys: "Shift+I" },
    { id: "gh4", label: "Apply Label", keys: "L" },
    { id: "gh5", label: "Assign Milestone", keys: "M" },
    { id: "gh6", label: "Toggle Reply", keys: "R" },
    { id: "gh7", label: "Issue List", keys: "G, I" },
    { id: "gh8", label: "PR List", keys: "G, P" },
    { id: "gh9", label: "Go to Code", keys: "G, C" },
    { id: "gh10", label: "Find File", keys: "T" },
    { id: "gh11", label: "Jump to Line", keys: "L" },
    { id: "gh12", label: "Switch Branch", keys: "W" },
  ],
  "Dev - GitHub Copilot": [
    { id: "cp1", label: "Trigger Complete", keys: "Ctrl+Shift+Ent" },
    { id: "cp2", label: "Scroll Suggest", keys: "Ctrl+Shift+Up/Dn" },
    { id: "cp3", label: "Fix Code", keys: "Ctrl+." },
    { id: "cp4", label: "Open Inline Chat", keys: "Ctrl+I" },
  ],
  "Creative - FL Studio": [
    { id: "fl1", label: "Play/Stop", keys: "Space" },
    { id: "fl2", label: "Step Sequencer", keys: "F6" },
    { id: "fl3", label: "Playlist", keys: "F5" },
    { id: "fl4", label: "Piano Roll", keys: "F7" },
    { id: "fl5", label: "Mixer", keys: "F9" },
    { id: "fl6", label: "Quantize", keys: "Alt+Q" },
    { id: "fl7", label: "Duplicate", keys: "Ctrl+B" },
    { id: "fl8", label: "Transpose Up", keys: "Shift+Up" },
    { id: "fl9", label: "Transpose Down", keys: "Shift+Down" },
    { id: "fl10", label: "Mute/Unmute", keys: "T" },
    { id: "fl11", label: "Slice Tool", keys: "C" },
    { id: "fl12", label: "Draw Tool", keys: "P" },
    { id: "fl13", label: "Paint Tool", keys: "B" },
    { id: "fl14", label: "Select All", keys: "Ctrl+A" },
    { id: "fl15", label: "Deselect", keys: "Ctrl+D" },
    { id: "fl16", label: "Save New Version", keys: "Ctrl+N" },
  ],
  "Creative - Canva": [
    { id: "ca1", label: "Add Text", keys: "T" },
    { id: "ca2", label: "Add Rect", keys: "R" },
    { id: "ca3", label: "Add Circle", keys: "C" },
    { id: "ca4", label: "Add Line", keys: "L" },
    { id: "ca5", label: "Toggle Case", keys: "Shift+Cmd+K" },
    { id: "ca6", label: "Lock Element", keys: "Shift+Cmd+L" },
    { id: "ca7", label: "Search Elements", keys: "/" },
    { id: "ca8", label: "Center Align", keys: "Shift+Cmd+C" },
    { id: "ca9", label: "Group", keys: "Cmd+G" },
    { id: "ca10", label: "Ungroup", keys: "Shift+Cmd+G" },
    { id: "ca11", label: "Bring Fwd", keys: "Cmd+]" },
    { id: "ca12", label: "Send Bkwd", keys: "Cmd+[" },
  ],
  "Productivity - Google Sheets": [
    { id: "gs1", label: "Paste Values", keys: "Ctrl+Shift+V" },
    { id: "gs2", label: "Insert Link", keys: "Ctrl+K" },
    { id: "gs3", label: "Insert Row Above", keys: "Alt+I, R" },
    { id: "gs4", label: "Insert Col Left", keys: "Alt+I, C" },
    { id: "gs5", label: "Format Number", keys: "Ctrl+Shift+1" },
    { id: "gs6", label: "Format Currency", keys: "Ctrl+Shift+4" },
    { id: "gs7", label: "Format Percent", keys: "Ctrl+Shift+5" },
    { id: "gs8", label: "Go to A1", keys: "Ctrl+Home" },
    { id: "gs9", label: "Go to Last", keys: "Ctrl+End" },
  ],
  "Productivity - Google Docs": [
    { id: "gd1", label: "Center Align", keys: "Ctrl+Shift+E" },
    { id: "gd2", label: "Left Align", keys: "Ctrl+Shift+L" },
    { id: "gd3", label: "Justify", keys: "Ctrl+Shift+J" },
    { id: "gd4", label: "Paste Plain", keys: "Ctrl+Shift+V" },
    { id: "gd5", label: "Heading 1", keys: "Ctrl+Alt+H" },
    { id: "gd6", label: "Table of Conts", keys: "Ctrl+Alt+T" },
    { id: "gd7", label: "Insert Comment", keys: "Ctrl+Alt+M" },
    { id: "gd8", label: "Bullet List", keys: "Ctrl+Shift+8" },
  ],
  "Productivity - Excel": [
    { id: "ex1", label: "Select Non-Empty", keys: "Ctrl+Shift+Arrow" },
    { id: "ex2", label: "Select Col Down", keys: "Ctrl+Shift+Down" },
    { id: "ex3", label: "Select Col", keys: "Ctrl+Space" },
    { id: "ex4", label: "Select Row", keys: "Shift+Space" },
    { id: "ex5", label: "Fill Down", keys: "Ctrl+D" },
    { id: "ex6", label: "Fill Right", keys: "Ctrl+R" },
    { id: "ex7", label: "Undo", keys: "Ctrl+Z" },
    { id: "ex8", label: "Calc All", keys: "F9" },
    { id: "ex9", label: "Apply Border", keys: "Alt+H, B" },
    { id: "ex10", label: "AutoSum", keys: "Alt+=" },
    { id: "ex11", label: "Insert Date", keys: "Ctrl+;" },
    { id: "ex12", label: "Insert Time", keys: "Ctrl+Shift+;" },
    { id: "ex13", label: "Format Cells", keys: "Ctrl+1" },
    { id: "ex14", label: "New Sheet", keys: "Shift+F11" },
    { id: "ex15", label: "Filter Toggle", keys: "Ctrl+Shift+L" },
    { id: "ex16", label: "Select Visible", keys: "Alt+;" },
  ],
  "Productivity - Word": [
    { id: "wd1", label: "Line Spacing", keys: "Ctrl+1/2/5" },
    { id: "wd2", label: "Increase Indent", keys: "Ctrl+M" },
    { id: "wd3", label: "Bullet List", keys: "Ctrl+Shift+L" },
    { id: "wd4", label: "Small Caps", keys: "Ctrl+Shift+K" },
    { id: "wd5", label: "Copy Format", keys: "Ctrl+Shift+C" },
    { id: "wd6", label: "Paste Format", keys: "Ctrl+Shift+V" },
    { id: "wd7", label: "Headings", keys: "Ctrl+Alt+1/2/3" },
  ],
  "Productivity - Acrobat Pro": [
    { id: "ap1", label: "New PDF", keys: "Ctrl+Shift+N" },
    { id: "ap2", label: "Rulers", keys: "Ctrl+R" },
    { id: "ap3", label: "Main Toolbar", keys: "Ctrl+Shift+H" },
    { id: "ap4", label: "Page View", keys: "Ctrl+U" },
    { id: "ap5", label: "Add Comment", keys: "Ctrl+Shift+M" },
    { id: "ap6", label: "Read Mode", keys: "Ctrl+H" },
    { id: "ap7", label: "Select Multi", keys: "Shift+Click" },
  ],
  "Project Mgmt - Linear": [
    { id: "ln1", label: "Issue Options", keys: "Space" },
    { id: "ln2", label: "Select Multi", keys: "Shift+Click" },
    { id: "ln3", label: "Assign", keys: "A" },
    { id: "ln4", label: "Move Project", keys: "M" },
    { id: "ln5", label: "Set Status", keys: "S" },
    { id: "ln6", label: "Set Priority", keys: "P" },
    { id: "ln7", label: "Export", keys: "Cmd+Shift+E" },
    { id: "ln8", label: "Archive", keys: "E" },
    { id: "ln9", label: "Reply", keys: "R" },
    { id: "ln10", label: "My Issues", keys: "G, M" },
    { id: "ln11", label: "Active Cycle", keys: "G, C" },
    { id: "ln12", label: "Backlog", keys: "G, B" },
    { id: "ln13", label: "Create Issue", keys: "C" },
  ],
  "System - Windows": [
    { id: "win1", label: "Screenshot Region", keys: "Win+Shift+S" },
    { id: "win2", label: "Clipboard History", keys: "Win+V" },
    { id: "win3", label: "Emoji Picker", keys: "Win+." },
    { id: "win4", label: "Lock Screen", keys: "Win+L" },
    { id: "win5", label: "Settings", keys: "Win+I" },
    { id: "win6", label: "File Explorer", keys: "Win+E" },
    { id: "win7", label: "Task Manager", keys: "Ctrl+Shift+Esc" },
    { id: "win8", label: "Snap Window L", keys: "Win+Left" },
    { id: "win9", label: "Snap Window R", keys: "Win+Right" },
    { id: "win10", label: "Show Desktop", keys: "Win+D" },
  ],
  "System - MacOS": [
    { id: "mac1", label: "Spotlight", keys: "Cmd+Space" },
    { id: "mac2", label: "Screenshot Region", keys: "Cmd+Shift+4" },
    { id: "mac3", label: "Emoji Picker", keys: "Cmd+Ctrl+Space" },
    { id: "mac4", label: "Force Quit", keys: "Opt+Cmd+Esc" },
    { id: "mac5", label: "Switch App", keys: "Cmd+Tab" },
    { id: "mac6", label: "Show Desktop", keys: "F11" },
    { id: "mac7", label: "Lock Screen", keys: "Ctrl+Cmd+Q" },
    { id: "mac8", label: "Dictation", keys: "F5" },
  ],
  "Browser - General": [
    { id: "br1", label: "New Tab", keys: "Ctrl+T" },
    { id: "br2", label: "Close Tab", keys: "Ctrl+W" },
    { id: "br3", label: "Reopen Tab", keys: "Ctrl+Shift+T" },
    { id: "br4", label: "Next Tab", keys: "Ctrl+Tab" },
    { id: "br5", label: "Prev Tab", keys: "Ctrl+Shift+Tab" },
    { id: "br6", label: "Find in Page", keys: "Ctrl+F" },
    { id: "br7", label: "History", keys: "Ctrl+H" },
    { id: "br8", label: "Downloads", keys: "Ctrl+J" },
    { id: "br9", label: "Incognito", keys: "Ctrl+Shift+N" },
    { id: "br10", label: "Focus URL", keys: "Ctrl+L" },
  ]
};
